### ISSUE TITLE
Refactor item() method argument signature

### ISSUE THREAD

**Issue by premasagar** [asyncjs/nodeventure#1]
Currently, it is:

``` js
item(roomName, itemName, respawnTime, descriptions)
```

To be consistent with the `room()` signature, it should be:

``` js
item(roomName, itemName, options)
```

where `options` can have:

``` js
{respawnTime: 1000, description: '', short: '', aliases: []}
```

And update all the scripts in the /world directory, and the [wiki reference page](https://github.com/asyncjs/nodeventure/wiki/Reference).

**Comment by almost** [comment]
Seems like this was done some time ago!
